// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"traceability/internal/biz"
	"traceability/internal/conf"
	"traceability/internal/data"
	"traceability/internal/server"
	"traceability/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	traceabilityRepo := data.NewTraceabilityRepo(dataData, logger)
	traceabilityUsecase := biz.NewTraceabilityUsecase(traceabilityRepo, logger)
	traceabilityService := service.NewTraceabilityService(traceabilityUsecase)
	grpcServer := server.NewGRPCServer(confServer, traceabilityService, logger)
	httpServer := server.NewHTTPServer(confServer, traceabilityService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
