server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: postgres://taksa:taksa_123@taksa-tsdb:5432/traceability_db?sslmode=disable
  redis:
    addr: taksa-tsdb:6379
    read_timeout: 0.2s
    write_timeout: 0.2s