// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: traceability/v1/traceability.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTraceabilityAddCapability = "/api.traceability.v1.Traceability/AddCapability"
const OperationTraceabilityCreateArea = "/api.traceability.v1.Traceability/CreateArea"
const OperationTraceabilityCreateEnterprise = "/api.traceability.v1.Traceability/CreateEnterprise"
const OperationTraceabilityCreateEquipmentClass = "/api.traceability.v1.Traceability/CreateEquipmentClass"
const OperationTraceabilityCreateLine = "/api.traceability.v1.Traceability/CreateLine"
const OperationTraceabilityCreateProductionUnit = "/api.traceability.v1.Traceability/CreateProductionUnit"
const OperationTraceabilityCreateSite = "/api.traceability.v1.Traceability/CreateSite"
const OperationTraceabilityDeleteArea = "/api.traceability.v1.Traceability/DeleteArea"
const OperationTraceabilityDeleteCapability = "/api.traceability.v1.Traceability/DeleteCapability"
const OperationTraceabilityDeleteEnterprise = "/api.traceability.v1.Traceability/DeleteEnterprise"
const OperationTraceabilityDeleteEquipment = "/api.traceability.v1.Traceability/DeleteEquipment"
const OperationTraceabilityDeleteEquipmentClass = "/api.traceability.v1.Traceability/DeleteEquipmentClass"
const OperationTraceabilityDeleteLine = "/api.traceability.v1.Traceability/DeleteLine"
const OperationTraceabilityDeleteProductionUnit = "/api.traceability.v1.Traceability/DeleteProductionUnit"
const OperationTraceabilityDeleteProperty = "/api.traceability.v1.Traceability/DeleteProperty"
const OperationTraceabilityDeleteSite = "/api.traceability.v1.Traceability/DeleteSite"
const OperationTraceabilityListAreas = "/api.traceability.v1.Traceability/ListAreas"
const OperationTraceabilityListCapabilities = "/api.traceability.v1.Traceability/ListCapabilities"
const OperationTraceabilityListEnterprises = "/api.traceability.v1.Traceability/ListEnterprises"
const OperationTraceabilityListEquipment = "/api.traceability.v1.Traceability/ListEquipment"
const OperationTraceabilityListEquipmentClasses = "/api.traceability.v1.Traceability/ListEquipmentClasses"
const OperationTraceabilityListLines = "/api.traceability.v1.Traceability/ListLines"
const OperationTraceabilityListLogs = "/api.traceability.v1.Traceability/ListLogs"
const OperationTraceabilityListProductionUnits = "/api.traceability.v1.Traceability/ListProductionUnits"
const OperationTraceabilityListProperties = "/api.traceability.v1.Traceability/ListProperties"
const OperationTraceabilityListSites = "/api.traceability.v1.Traceability/ListSites"
const OperationTraceabilityLogEvent = "/api.traceability.v1.Traceability/LogEvent"
const OperationTraceabilityRegisterEquipment = "/api.traceability.v1.Traceability/RegisterEquipment"
const OperationTraceabilitySetProperty = "/api.traceability.v1.Traceability/SetProperty"
const OperationTraceabilityUpdateArea = "/api.traceability.v1.Traceability/UpdateArea"
const OperationTraceabilityUpdateCapability = "/api.traceability.v1.Traceability/UpdateCapability"
const OperationTraceabilityUpdateEnterprise = "/api.traceability.v1.Traceability/UpdateEnterprise"
const OperationTraceabilityUpdateEquipment = "/api.traceability.v1.Traceability/UpdateEquipment"
const OperationTraceabilityUpdateEquipmentClass = "/api.traceability.v1.Traceability/UpdateEquipmentClass"
const OperationTraceabilityUpdateLine = "/api.traceability.v1.Traceability/UpdateLine"
const OperationTraceabilityUpdateProductionUnit = "/api.traceability.v1.Traceability/UpdateProductionUnit"
const OperationTraceabilityUpdateProperty = "/api.traceability.v1.Traceability/UpdateProperty"
const OperationTraceabilityUpdateSite = "/api.traceability.v1.Traceability/UpdateSite"

type TraceabilityHTTPServer interface {
	// AddCapability 8. Equipment Capability Management
	AddCapability(context.Context, *AddCapabilityRequest) (*AddCapabilityReply, error)
	// CreateArea 3. Area Management
	CreateArea(context.Context, *CreateAreaRequest) (*CreateAreaReply, error)
	// CreateEnterprise 1. Enterprise Management
	CreateEnterprise(context.Context, *CreateEnterpriseRequest) (*CreateEnterpriseReply, error)
	// CreateEquipmentClass 6. Equipment Class Management
	CreateEquipmentClass(context.Context, *CreateEquipmentClassRequest) (*CreateEquipmentClassReply, error)
	// CreateLine 4. Production Line Management
	CreateLine(context.Context, *CreateLineRequest) (*CreateLineReply, error)
	// CreateProductionUnit 5. Production Unit Management
	CreateProductionUnit(context.Context, *CreateProductionUnitRequest) (*CreateProductionUnitReply, error)
	// CreateSite 2. Site Management
	CreateSite(context.Context, *CreateSiteRequest) (*CreateSiteReply, error)
	DeleteArea(context.Context, *DeleteAreaRequest) (*DeleteAreaReply, error)
	DeleteCapability(context.Context, *DeleteCapabilityRequest) (*DeleteCapabilityReply, error)
	DeleteEnterprise(context.Context, *DeleteEnterpriseRequest) (*DeleteEnterpriseReply, error)
	DeleteEquipment(context.Context, *DeleteEquipmentRequest) (*DeleteEquipmentReply, error)
	DeleteEquipmentClass(context.Context, *DeleteEquipmentClassRequest) (*DeleteEquipmentClassReply, error)
	DeleteLine(context.Context, *DeleteLineRequest) (*DeleteLineReply, error)
	DeleteProductionUnit(context.Context, *DeleteProductionUnitRequest) (*DeleteProductionUnitReply, error)
	DeleteProperty(context.Context, *DeletePropertyRequest) (*DeletePropertyReply, error)
	DeleteSite(context.Context, *DeleteSiteRequest) (*DeleteSiteReply, error)
	ListAreas(context.Context, *ListAreasRequest) (*ListAreasReply, error)
	ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesReply, error)
	ListEnterprises(context.Context, *ListEnterprisesRequest) (*ListEnterprisesReply, error)
	ListEquipment(context.Context, *ListEquipmentRequest) (*ListEquipmentReply, error)
	ListEquipmentClasses(context.Context, *ListEquipmentClassesRequest) (*ListEquipmentClassesReply, error)
	ListLines(context.Context, *ListLinesRequest) (*ListLinesReply, error)
	ListLogs(context.Context, *ListLogsRequest) (*ListLogsReply, error)
	ListProductionUnits(context.Context, *ListProductionUnitsRequest) (*ListProductionUnitsReply, error)
	ListProperties(context.Context, *ListPropertiesRequest) (*ListPropertiesReply, error)
	ListSites(context.Context, *ListSitesRequest) (*ListSitesReply, error)
	// LogEvent 10. Traceability Logs
	LogEvent(context.Context, *LogEventRequest) (*LogEventReply, error)
	// RegisterEquipment 7. Equipment Master Management
	RegisterEquipment(context.Context, *RegisterEquipmentRequest) (*RegisterEquipmentReply, error)
	// SetProperty 9. Equipment Property Management
	SetProperty(context.Context, *SetPropertyRequest) (*SetPropertyReply, error)
	UpdateArea(context.Context, *UpdateAreaRequest) (*UpdateAreaReply, error)
	UpdateCapability(context.Context, *UpdateCapabilityRequest) (*UpdateCapabilityReply, error)
	UpdateEnterprise(context.Context, *UpdateEnterpriseRequest) (*UpdateEnterpriseReply, error)
	UpdateEquipment(context.Context, *UpdateEquipmentRequest) (*UpdateEquipmentReply, error)
	UpdateEquipmentClass(context.Context, *UpdateEquipmentClassRequest) (*UpdateEquipmentClassReply, error)
	UpdateLine(context.Context, *UpdateLineRequest) (*UpdateLineReply, error)
	UpdateProductionUnit(context.Context, *UpdateProductionUnitRequest) (*UpdateProductionUnitReply, error)
	UpdateProperty(context.Context, *UpdatePropertyRequest) (*UpdatePropertyReply, error)
	UpdateSite(context.Context, *UpdateSiteRequest) (*UpdateSiteReply, error)
}

func RegisterTraceabilityHTTPServer(s *http.Server, srv TraceabilityHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/traceability/enterprises", _Traceability_CreateEnterprise0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/enterprises", _Traceability_ListEnterprises0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/enterprises/{id}", _Traceability_UpdateEnterprise0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/enterprises/{id}", _Traceability_DeleteEnterprise0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/sites", _Traceability_CreateSite0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/sites", _Traceability_ListSites0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/sites/{id}", _Traceability_UpdateSite0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/sites/{id}", _Traceability_DeleteSite0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/areas", _Traceability_CreateArea0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/areas", _Traceability_ListAreas0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/areas/{id}", _Traceability_UpdateArea0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/areas/{id}", _Traceability_DeleteArea0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/lines", _Traceability_CreateLine0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/lines", _Traceability_ListLines0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/lines/{id}", _Traceability_UpdateLine0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/lines/{id}", _Traceability_DeleteLine0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/production-units", _Traceability_CreateProductionUnit0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/production-units", _Traceability_ListProductionUnits0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/production-units/{id}", _Traceability_UpdateProductionUnit0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/production-units/{id}", _Traceability_DeleteProductionUnit0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/equipment-classes", _Traceability_CreateEquipmentClass0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/equipment-classes", _Traceability_ListEquipmentClasses0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/equipment-classes/{id}", _Traceability_UpdateEquipmentClass0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/equipment-classes/{id}", _Traceability_DeleteEquipmentClass0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/equipment", _Traceability_RegisterEquipment0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/equipment", _Traceability_ListEquipment0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/equipment/{id}", _Traceability_UpdateEquipment0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/equipment/{id}", _Traceability_DeleteEquipment0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/equipment/{equipment_id}/capabilities", _Traceability_AddCapability0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/equipment/{equipment_id}/capabilities", _Traceability_ListCapabilities0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/equipment/{equipment_id}/capabilities/{id}", _Traceability_UpdateCapability0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/equipment/{equipment_id}/capabilities/{id}", _Traceability_DeleteCapability0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/equipment/{equipment_id}/properties", _Traceability_SetProperty0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/equipment/{equipment_id}/properties", _Traceability_ListProperties0_HTTP_Handler(srv))
	r.PATCH("/api/v1/traceability/equipment/{equipment_id}/properties/{id}", _Traceability_UpdateProperty0_HTTP_Handler(srv))
	r.DELETE("/api/v1/traceability/equipment/{equipment_id}/properties/{id}", _Traceability_DeleteProperty0_HTTP_Handler(srv))
	r.POST("/api/v1/traceability/logs", _Traceability_LogEvent0_HTTP_Handler(srv))
	r.GET("/api/v1/traceability/logs", _Traceability_ListLogs0_HTTP_Handler(srv))
}

func _Traceability_CreateEnterprise0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEnterpriseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityCreateEnterprise)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEnterprise(ctx, req.(*CreateEnterpriseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEnterpriseReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListEnterprises0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEnterprisesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListEnterprises)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEnterprises(ctx, req.(*ListEnterprisesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEnterprisesReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateEnterprise0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEnterpriseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateEnterprise)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEnterprise(ctx, req.(*UpdateEnterpriseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEnterpriseReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteEnterprise0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEnterpriseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteEnterprise)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEnterprise(ctx, req.(*DeleteEnterpriseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEnterpriseReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_CreateSite0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSiteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityCreateSite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSite(ctx, req.(*CreateSiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSiteReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListSites0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSitesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListSites)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSites(ctx, req.(*ListSitesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSitesReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateSite0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSiteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateSite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSite(ctx, req.(*UpdateSiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSiteReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteSite0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSiteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteSite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSite(ctx, req.(*DeleteSiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSiteReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_CreateArea0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAreaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityCreateArea)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateArea(ctx, req.(*CreateAreaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAreaReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListAreas0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAreasRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListAreas)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAreas(ctx, req.(*ListAreasRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAreasReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateArea0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAreaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateArea)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateArea(ctx, req.(*UpdateAreaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAreaReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteArea0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAreaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteArea)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteArea(ctx, req.(*DeleteAreaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAreaReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_CreateLine0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateLineRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityCreateLine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateLine(ctx, req.(*CreateLineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateLineReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListLines0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLinesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListLines)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLines(ctx, req.(*ListLinesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLinesReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateLine0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateLineRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateLine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateLine(ctx, req.(*UpdateLineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateLineReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteLine0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteLineRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteLine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteLine(ctx, req.(*DeleteLineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteLineReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_CreateProductionUnit0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProductionUnitRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityCreateProductionUnit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProductionUnit(ctx, req.(*CreateProductionUnitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProductionUnitReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListProductionUnits0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductionUnitsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListProductionUnits)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProductionUnits(ctx, req.(*ListProductionUnitsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductionUnitsReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateProductionUnit0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProductionUnitRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateProductionUnit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProductionUnit(ctx, req.(*UpdateProductionUnitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProductionUnitReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteProductionUnit0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProductionUnitRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteProductionUnit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProductionUnit(ctx, req.(*DeleteProductionUnitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteProductionUnitReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_CreateEquipmentClass0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEquipmentClassRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityCreateEquipmentClass)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEquipmentClass(ctx, req.(*CreateEquipmentClassRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEquipmentClassReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListEquipmentClasses0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEquipmentClassesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListEquipmentClasses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEquipmentClasses(ctx, req.(*ListEquipmentClassesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEquipmentClassesReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateEquipmentClass0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEquipmentClassRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateEquipmentClass)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEquipmentClass(ctx, req.(*UpdateEquipmentClassRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEquipmentClassReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteEquipmentClass0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEquipmentClassRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteEquipmentClass)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEquipmentClass(ctx, req.(*DeleteEquipmentClassRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEquipmentClassReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_RegisterEquipment0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterEquipmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityRegisterEquipment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterEquipment(ctx, req.(*RegisterEquipmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterEquipmentReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListEquipment0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEquipmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListEquipment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEquipment(ctx, req.(*ListEquipmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEquipmentReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateEquipment0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEquipmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateEquipment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEquipment(ctx, req.(*UpdateEquipmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEquipmentReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteEquipment0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEquipmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteEquipment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEquipment(ctx, req.(*DeleteEquipmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEquipmentReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_AddCapability0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddCapabilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityAddCapability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddCapability(ctx, req.(*AddCapabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddCapabilityReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListCapabilities0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCapabilitiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListCapabilities)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCapabilities(ctx, req.(*ListCapabilitiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCapabilitiesReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateCapability0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCapabilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateCapability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCapability(ctx, req.(*UpdateCapabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCapabilityReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteCapability0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCapabilityRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteCapability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCapability(ctx, req.(*DeleteCapabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCapabilityReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_SetProperty0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetPropertyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilitySetProperty)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetProperty(ctx, req.(*SetPropertyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetPropertyReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListProperties0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPropertiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListProperties)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProperties(ctx, req.(*ListPropertiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPropertiesReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_UpdateProperty0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePropertyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityUpdateProperty)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProperty(ctx, req.(*UpdatePropertyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePropertyReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_DeleteProperty0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePropertyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityDeleteProperty)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProperty(ctx, req.(*DeletePropertyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePropertyReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_LogEvent0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityLogEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LogEvent(ctx, req.(*LogEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogEventReply)
		return ctx.Result(200, reply)
	}
}

func _Traceability_ListLogs0_HTTP_Handler(srv TraceabilityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTraceabilityListLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLogs(ctx, req.(*ListLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLogsReply)
		return ctx.Result(200, reply)
	}
}

type TraceabilityHTTPClient interface {
	// AddCapability 8. Equipment Capability Management
	AddCapability(ctx context.Context, req *AddCapabilityRequest, opts ...http.CallOption) (rsp *AddCapabilityReply, err error)
	// CreateArea 3. Area Management
	CreateArea(ctx context.Context, req *CreateAreaRequest, opts ...http.CallOption) (rsp *CreateAreaReply, err error)
	// CreateEnterprise 1. Enterprise Management
	CreateEnterprise(ctx context.Context, req *CreateEnterpriseRequest, opts ...http.CallOption) (rsp *CreateEnterpriseReply, err error)
	// CreateEquipmentClass 6. Equipment Class Management
	CreateEquipmentClass(ctx context.Context, req *CreateEquipmentClassRequest, opts ...http.CallOption) (rsp *CreateEquipmentClassReply, err error)
	// CreateLine 4. Production Line Management
	CreateLine(ctx context.Context, req *CreateLineRequest, opts ...http.CallOption) (rsp *CreateLineReply, err error)
	// CreateProductionUnit 5. Production Unit Management
	CreateProductionUnit(ctx context.Context, req *CreateProductionUnitRequest, opts ...http.CallOption) (rsp *CreateProductionUnitReply, err error)
	// CreateSite 2. Site Management
	CreateSite(ctx context.Context, req *CreateSiteRequest, opts ...http.CallOption) (rsp *CreateSiteReply, err error)
	DeleteArea(ctx context.Context, req *DeleteAreaRequest, opts ...http.CallOption) (rsp *DeleteAreaReply, err error)
	DeleteCapability(ctx context.Context, req *DeleteCapabilityRequest, opts ...http.CallOption) (rsp *DeleteCapabilityReply, err error)
	DeleteEnterprise(ctx context.Context, req *DeleteEnterpriseRequest, opts ...http.CallOption) (rsp *DeleteEnterpriseReply, err error)
	DeleteEquipment(ctx context.Context, req *DeleteEquipmentRequest, opts ...http.CallOption) (rsp *DeleteEquipmentReply, err error)
	DeleteEquipmentClass(ctx context.Context, req *DeleteEquipmentClassRequest, opts ...http.CallOption) (rsp *DeleteEquipmentClassReply, err error)
	DeleteLine(ctx context.Context, req *DeleteLineRequest, opts ...http.CallOption) (rsp *DeleteLineReply, err error)
	DeleteProductionUnit(ctx context.Context, req *DeleteProductionUnitRequest, opts ...http.CallOption) (rsp *DeleteProductionUnitReply, err error)
	DeleteProperty(ctx context.Context, req *DeletePropertyRequest, opts ...http.CallOption) (rsp *DeletePropertyReply, err error)
	DeleteSite(ctx context.Context, req *DeleteSiteRequest, opts ...http.CallOption) (rsp *DeleteSiteReply, err error)
	ListAreas(ctx context.Context, req *ListAreasRequest, opts ...http.CallOption) (rsp *ListAreasReply, err error)
	ListCapabilities(ctx context.Context, req *ListCapabilitiesRequest, opts ...http.CallOption) (rsp *ListCapabilitiesReply, err error)
	ListEnterprises(ctx context.Context, req *ListEnterprisesRequest, opts ...http.CallOption) (rsp *ListEnterprisesReply, err error)
	ListEquipment(ctx context.Context, req *ListEquipmentRequest, opts ...http.CallOption) (rsp *ListEquipmentReply, err error)
	ListEquipmentClasses(ctx context.Context, req *ListEquipmentClassesRequest, opts ...http.CallOption) (rsp *ListEquipmentClassesReply, err error)
	ListLines(ctx context.Context, req *ListLinesRequest, opts ...http.CallOption) (rsp *ListLinesReply, err error)
	ListLogs(ctx context.Context, req *ListLogsRequest, opts ...http.CallOption) (rsp *ListLogsReply, err error)
	ListProductionUnits(ctx context.Context, req *ListProductionUnitsRequest, opts ...http.CallOption) (rsp *ListProductionUnitsReply, err error)
	ListProperties(ctx context.Context, req *ListPropertiesRequest, opts ...http.CallOption) (rsp *ListPropertiesReply, err error)
	ListSites(ctx context.Context, req *ListSitesRequest, opts ...http.CallOption) (rsp *ListSitesReply, err error)
	// LogEvent 10. Traceability Logs
	LogEvent(ctx context.Context, req *LogEventRequest, opts ...http.CallOption) (rsp *LogEventReply, err error)
	// RegisterEquipment 7. Equipment Master Management
	RegisterEquipment(ctx context.Context, req *RegisterEquipmentRequest, opts ...http.CallOption) (rsp *RegisterEquipmentReply, err error)
	// SetProperty 9. Equipment Property Management
	SetProperty(ctx context.Context, req *SetPropertyRequest, opts ...http.CallOption) (rsp *SetPropertyReply, err error)
	UpdateArea(ctx context.Context, req *UpdateAreaRequest, opts ...http.CallOption) (rsp *UpdateAreaReply, err error)
	UpdateCapability(ctx context.Context, req *UpdateCapabilityRequest, opts ...http.CallOption) (rsp *UpdateCapabilityReply, err error)
	UpdateEnterprise(ctx context.Context, req *UpdateEnterpriseRequest, opts ...http.CallOption) (rsp *UpdateEnterpriseReply, err error)
	UpdateEquipment(ctx context.Context, req *UpdateEquipmentRequest, opts ...http.CallOption) (rsp *UpdateEquipmentReply, err error)
	UpdateEquipmentClass(ctx context.Context, req *UpdateEquipmentClassRequest, opts ...http.CallOption) (rsp *UpdateEquipmentClassReply, err error)
	UpdateLine(ctx context.Context, req *UpdateLineRequest, opts ...http.CallOption) (rsp *UpdateLineReply, err error)
	UpdateProductionUnit(ctx context.Context, req *UpdateProductionUnitRequest, opts ...http.CallOption) (rsp *UpdateProductionUnitReply, err error)
	UpdateProperty(ctx context.Context, req *UpdatePropertyRequest, opts ...http.CallOption) (rsp *UpdatePropertyReply, err error)
	UpdateSite(ctx context.Context, req *UpdateSiteRequest, opts ...http.CallOption) (rsp *UpdateSiteReply, err error)
}

type TraceabilityHTTPClientImpl struct {
	cc *http.Client
}

func NewTraceabilityHTTPClient(client *http.Client) TraceabilityHTTPClient {
	return &TraceabilityHTTPClientImpl{client}
}

// AddCapability 8. Equipment Capability Management
func (c *TraceabilityHTTPClientImpl) AddCapability(ctx context.Context, in *AddCapabilityRequest, opts ...http.CallOption) (*AddCapabilityReply, error) {
	var out AddCapabilityReply
	pattern := "/api/v1/traceability/equipment/{equipment_id}/capabilities"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityAddCapability))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateArea 3. Area Management
func (c *TraceabilityHTTPClientImpl) CreateArea(ctx context.Context, in *CreateAreaRequest, opts ...http.CallOption) (*CreateAreaReply, error) {
	var out CreateAreaReply
	pattern := "/api/v1/traceability/areas"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityCreateArea))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateEnterprise 1. Enterprise Management
func (c *TraceabilityHTTPClientImpl) CreateEnterprise(ctx context.Context, in *CreateEnterpriseRequest, opts ...http.CallOption) (*CreateEnterpriseReply, error) {
	var out CreateEnterpriseReply
	pattern := "/api/v1/traceability/enterprises"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityCreateEnterprise))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateEquipmentClass 6. Equipment Class Management
func (c *TraceabilityHTTPClientImpl) CreateEquipmentClass(ctx context.Context, in *CreateEquipmentClassRequest, opts ...http.CallOption) (*CreateEquipmentClassReply, error) {
	var out CreateEquipmentClassReply
	pattern := "/api/v1/traceability/equipment-classes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityCreateEquipmentClass))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateLine 4. Production Line Management
func (c *TraceabilityHTTPClientImpl) CreateLine(ctx context.Context, in *CreateLineRequest, opts ...http.CallOption) (*CreateLineReply, error) {
	var out CreateLineReply
	pattern := "/api/v1/traceability/lines"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityCreateLine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateProductionUnit 5. Production Unit Management
func (c *TraceabilityHTTPClientImpl) CreateProductionUnit(ctx context.Context, in *CreateProductionUnitRequest, opts ...http.CallOption) (*CreateProductionUnitReply, error) {
	var out CreateProductionUnitReply
	pattern := "/api/v1/traceability/production-units"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityCreateProductionUnit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSite 2. Site Management
func (c *TraceabilityHTTPClientImpl) CreateSite(ctx context.Context, in *CreateSiteRequest, opts ...http.CallOption) (*CreateSiteReply, error) {
	var out CreateSiteReply
	pattern := "/api/v1/traceability/sites"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityCreateSite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteArea(ctx context.Context, in *DeleteAreaRequest, opts ...http.CallOption) (*DeleteAreaReply, error) {
	var out DeleteAreaReply
	pattern := "/api/v1/traceability/areas/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteArea))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteCapability(ctx context.Context, in *DeleteCapabilityRequest, opts ...http.CallOption) (*DeleteCapabilityReply, error) {
	var out DeleteCapabilityReply
	pattern := "/api/v1/traceability/equipment/{equipment_id}/capabilities/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteCapability))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteEnterprise(ctx context.Context, in *DeleteEnterpriseRequest, opts ...http.CallOption) (*DeleteEnterpriseReply, error) {
	var out DeleteEnterpriseReply
	pattern := "/api/v1/traceability/enterprises/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteEnterprise))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteEquipment(ctx context.Context, in *DeleteEquipmentRequest, opts ...http.CallOption) (*DeleteEquipmentReply, error) {
	var out DeleteEquipmentReply
	pattern := "/api/v1/traceability/equipment/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteEquipment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteEquipmentClass(ctx context.Context, in *DeleteEquipmentClassRequest, opts ...http.CallOption) (*DeleteEquipmentClassReply, error) {
	var out DeleteEquipmentClassReply
	pattern := "/api/v1/traceability/equipment-classes/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteEquipmentClass))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteLine(ctx context.Context, in *DeleteLineRequest, opts ...http.CallOption) (*DeleteLineReply, error) {
	var out DeleteLineReply
	pattern := "/api/v1/traceability/lines/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteLine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteProductionUnit(ctx context.Context, in *DeleteProductionUnitRequest, opts ...http.CallOption) (*DeleteProductionUnitReply, error) {
	var out DeleteProductionUnitReply
	pattern := "/api/v1/traceability/production-units/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteProductionUnit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteProperty(ctx context.Context, in *DeletePropertyRequest, opts ...http.CallOption) (*DeletePropertyReply, error) {
	var out DeletePropertyReply
	pattern := "/api/v1/traceability/equipment/{equipment_id}/properties/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteProperty))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) DeleteSite(ctx context.Context, in *DeleteSiteRequest, opts ...http.CallOption) (*DeleteSiteReply, error) {
	var out DeleteSiteReply
	pattern := "/api/v1/traceability/sites/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityDeleteSite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListAreas(ctx context.Context, in *ListAreasRequest, opts ...http.CallOption) (*ListAreasReply, error) {
	var out ListAreasReply
	pattern := "/api/v1/traceability/areas"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListAreas))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...http.CallOption) (*ListCapabilitiesReply, error) {
	var out ListCapabilitiesReply
	pattern := "/api/v1/traceability/equipment/{equipment_id}/capabilities"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListCapabilities))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListEnterprises(ctx context.Context, in *ListEnterprisesRequest, opts ...http.CallOption) (*ListEnterprisesReply, error) {
	var out ListEnterprisesReply
	pattern := "/api/v1/traceability/enterprises"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListEnterprises))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListEquipment(ctx context.Context, in *ListEquipmentRequest, opts ...http.CallOption) (*ListEquipmentReply, error) {
	var out ListEquipmentReply
	pattern := "/api/v1/traceability/equipment"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListEquipment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListEquipmentClasses(ctx context.Context, in *ListEquipmentClassesRequest, opts ...http.CallOption) (*ListEquipmentClassesReply, error) {
	var out ListEquipmentClassesReply
	pattern := "/api/v1/traceability/equipment-classes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListEquipmentClasses))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListLines(ctx context.Context, in *ListLinesRequest, opts ...http.CallOption) (*ListLinesReply, error) {
	var out ListLinesReply
	pattern := "/api/v1/traceability/lines"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListLines))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListLogs(ctx context.Context, in *ListLogsRequest, opts ...http.CallOption) (*ListLogsReply, error) {
	var out ListLogsReply
	pattern := "/api/v1/traceability/logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListProductionUnits(ctx context.Context, in *ListProductionUnitsRequest, opts ...http.CallOption) (*ListProductionUnitsReply, error) {
	var out ListProductionUnitsReply
	pattern := "/api/v1/traceability/production-units"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListProductionUnits))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListProperties(ctx context.Context, in *ListPropertiesRequest, opts ...http.CallOption) (*ListPropertiesReply, error) {
	var out ListPropertiesReply
	pattern := "/api/v1/traceability/equipment/{equipment_id}/properties"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListProperties))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) ListSites(ctx context.Context, in *ListSitesRequest, opts ...http.CallOption) (*ListSitesReply, error) {
	var out ListSitesReply
	pattern := "/api/v1/traceability/sites"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTraceabilityListSites))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LogEvent 10. Traceability Logs
func (c *TraceabilityHTTPClientImpl) LogEvent(ctx context.Context, in *LogEventRequest, opts ...http.CallOption) (*LogEventReply, error) {
	var out LogEventReply
	pattern := "/api/v1/traceability/logs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityLogEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RegisterEquipment 7. Equipment Master Management
func (c *TraceabilityHTTPClientImpl) RegisterEquipment(ctx context.Context, in *RegisterEquipmentRequest, opts ...http.CallOption) (*RegisterEquipmentReply, error) {
	var out RegisterEquipmentReply
	pattern := "/api/v1/traceability/equipment"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityRegisterEquipment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetProperty 9. Equipment Property Management
func (c *TraceabilityHTTPClientImpl) SetProperty(ctx context.Context, in *SetPropertyRequest, opts ...http.CallOption) (*SetPropertyReply, error) {
	var out SetPropertyReply
	pattern := "/api/v1/traceability/equipment/{equipment_id}/properties"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilitySetProperty))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateArea(ctx context.Context, in *UpdateAreaRequest, opts ...http.CallOption) (*UpdateAreaReply, error) {
	var out UpdateAreaReply
	pattern := "/api/v1/traceability/areas/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateArea))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateCapability(ctx context.Context, in *UpdateCapabilityRequest, opts ...http.CallOption) (*UpdateCapabilityReply, error) {
	var out UpdateCapabilityReply
	pattern := "/api/v1/traceability/equipment/{equipment_id}/capabilities/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateCapability))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateEnterprise(ctx context.Context, in *UpdateEnterpriseRequest, opts ...http.CallOption) (*UpdateEnterpriseReply, error) {
	var out UpdateEnterpriseReply
	pattern := "/api/v1/traceability/enterprises/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateEnterprise))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateEquipment(ctx context.Context, in *UpdateEquipmentRequest, opts ...http.CallOption) (*UpdateEquipmentReply, error) {
	var out UpdateEquipmentReply
	pattern := "/api/v1/traceability/equipment/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateEquipment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateEquipmentClass(ctx context.Context, in *UpdateEquipmentClassRequest, opts ...http.CallOption) (*UpdateEquipmentClassReply, error) {
	var out UpdateEquipmentClassReply
	pattern := "/api/v1/traceability/equipment-classes/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateEquipmentClass))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateLine(ctx context.Context, in *UpdateLineRequest, opts ...http.CallOption) (*UpdateLineReply, error) {
	var out UpdateLineReply
	pattern := "/api/v1/traceability/lines/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateLine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateProductionUnit(ctx context.Context, in *UpdateProductionUnitRequest, opts ...http.CallOption) (*UpdateProductionUnitReply, error) {
	var out UpdateProductionUnitReply
	pattern := "/api/v1/traceability/production-units/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateProductionUnit))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateProperty(ctx context.Context, in *UpdatePropertyRequest, opts ...http.CallOption) (*UpdatePropertyReply, error) {
	var out UpdatePropertyReply
	pattern := "/api/v1/traceability/equipment/{equipment_id}/properties/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateProperty))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TraceabilityHTTPClientImpl) UpdateSite(ctx context.Context, in *UpdateSiteRequest, opts ...http.CallOption) (*UpdateSiteReply, error) {
	var out UpdateSiteReply
	pattern := "/api/v1/traceability/sites/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTraceabilityUpdateSite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
